openapi: 3.0.3
info:
  title: Petsitter API
  version: "0.1"
  description: |-
    This is a set of APIs for the Petsitter Application (which 
    consists of a MongoDB database, a Node.js backend and a 
    React.js frontend).  
  
  contact:
    name: Matt H.
    url: https://github.com/hollowmatt/petsitter
  license:
    url: https://www.apache.org/licenses/LICENSE-2.0.html
    name: Apache 2.0
paths: {}
components:
  schemas: 
    User: 
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        full_name:
          type: string
        roles:
          type: array
          items:
            type: string
    Job:
      type: object
      properties:
        id: 
          type: integer
        creator_user_id:
          type: integer
        start_time:
          type: string
        activity:
          type: string
        Pet:
          $ref: '#/components/schemas/Pet'
    Pet:
      type: object
      properties:
        pet_type:
          type: string
        name: 
          type: string
        age:
          type: integer
        breed:
          type: string
        size:
          type: string
    JobApplication:
      type: object
      properties:
        id: 
          type: integer
        status:
          type: string
        user_id:
          type: integer
        job_id:
          type: integer