openapi: 3.0.3
info:
  title: Petsitter API
  version: "0.1"
  description: |-
    This is a set of APIs for the Petsitter Application (which 
    consists of a MongoDB database, a Node.js backend and a 
    React.js frontend).  
  
  contact:
    name: Matt H.
    url: https://github.com/hollowmatt/petsitter
  license:
    url: https://www.apache.org/licenses/LICENSE-2.0.html
    name: Apache 2.0
tags:
  - name: Users
    description: Users of the Petsitter system (can be owner, petsitter, admin)
  - name: Jobs
    description: Jobs created by owners to have their pet looked after.
  - name: Job Applications
    description: Job applications by a pet sitter for a job.
paths:
  /users:
    post:
      tags:
        - Users
      summary: Register a user
      responses:
        '201':
          description: Creeated
          headers:
            Location:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
  /users/{id}:
   parameters:
     - schema:
         type: integer
       name: id
       in: path
       required: true
   get:
     tags:
      - Users
     summary: View User
     responses:
       '200':
         description: OK
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/User'
   put:
     tags:
      - Users
     summary: Modify User
     responses:
       '200':
         description: OK
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/User'
     requestBody:
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/User'
   delete:
     tags:  
      - Users
     summary: Delete User
     responses:
       '204':
         description: No Content
  /users/{id}/jobs:
   parameters:
     - schema:
         type: integer
       name: id
       in: path
       required: true
   get:
     tags:
      - Jobs
     summary: List jobs for User
     responses:
       '200':
         description: OK
         content:
           application/json:
             schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    $ref: '#/components/schemas/Job'
  /jobs:
    get:
      tags:
        - Jobs
      summary: List all jobs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Job'
    post:
      tags:
        - Jobs
      summary: Create a job
      responses:
        '201':
          description: created
          headers:
            Location:
              schema: 
                type: string
      requestBody:
        content:  
          application/json:
            schema:
              $ref: '#/components/schemas/Job'
  /jobs/{id}:
   parameters:
     - schema:
         type: integer
       name: id
       in: path
       required: true
   get:
     tags:
      - Jobs
     summary: View Job
     responses:
       '200':
         description: OK
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Job'
   put:
     tags:
      - Jobs
     summary: Modify Job
     responses:
       '200':
         description: OK
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Job'
     requestBody:
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/Job'
  /jobs/{id}/job-applications:
   parameters:
     - schema:
         type: integer
       name: id
       in: path
       required: true
   get:
     tags:
      - Job Applications
     summary: List Applications For Job
     responses:
       '200':
         description: OK
         content:
           application/json:
             schema:
               type: object
               properties:
                 items:
                   type: array
                   items:
                     $ref: '#/components/schemas/JobApplication'
   post:
      tags:
        - Job Applications
      summary: Create Job Application
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobApplication'
  /job-applications/{id}:
   parameters:
     - schema:
         type: integer
       name: id
       in: path
       required: true
   put:
     tags:
      - Job Applications
     summary: Modify Job Application
     requestBody:
       description: Update the application details
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/JobApplication'

     responses:
       '200':
         description: OK
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/JobApplication'
            
components:
  schemas: 
    User: 
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        full_name:
          type: string
        roles:
          type: array
          items:
            type: string
    Job:
      type: object
      properties:
        id: 
          type: integer
        creator_user_id:
          type: integer
        start_time:
          type: string
        activity:
          type: string
        Pet:
          $ref: '#/components/schemas/Pet'
    Pet:
      type: object
      properties:
        pet_type:
          type: string
        name: 
          type: string
        age:
          type: integer
        breed:
          type: string
        size:
          type: string
    JobApplication:
      type: object
      properties:
        id: 
          type: integer
        status:
          type: string
        user_id:
          type: integer
        job_id:
          type: integer

 